### ISSUE TITLE
Instructions on how to Import Videos

### ISSUE THREAD

**Issue by UntotenTheo** [Luna5829/CG-Video-Display#1]
On the Thunderstore page and here, the mod description states that the mod is capable of displaying custom videos on the Cyber Grind Display Board, but instructions aren't present on how to do so.

I'm humbly requesting that instructions be added along with relevant information such as what file formats are supported, if audio from the video plays, so on and so forth.

Thank you for reading :]

**Comment by Luna5829** [comment]
there's a video path section in the config, you need to launch the game with the mod, then the config file will appear in which you can set the video path

**Comment by UntotenTheo** [comment]
thanks chief
i still think you should put these instructions on the Thunderstore page so people can immediately figure out how to add their own videos

**Comment by Luna5829** [comment]
i mean i feel like it's pretty obvious that you need to put the video path in the config cuz that's literally the only way it could be done lol
