### ISSUE TITLE
Unexpected Crashing & Stuttery Video

### ISSUE THREAD

**Issue by UntotenTheo** [Luna5829/CG-Video-Display#3]
im just as surprised as you are

https://github.com/Luna5829/CG-Video-Display/assets/75056493/606aa32b-95a9-42fe-9ef2-f65369cc141c

the game crashes when trying to loop this specific video, im unsure if this occurs for other people although
another issue is that this video (and any iteration of it that ive edited, 1920x1920, 60fps, 30fps, 24fps, 12fps) has all resulted in a very stuttery video

it appears that the crashes only occurred recently on 24fps and 12fps videos, which is weird

i dont have any additional information to share, if i can ill get a peek at the console to figure out what went wrong though
if i find anything, ill send them over here

**Comment by Luna5829** [comment]
it works perfectly fine for me
are you sure you set the width and height of the video to the correct 600x600

**Comment by UntotenTheo** [comment]
yep, dimensions are correct
ill go test it out again i guess

**Comment by UntotenTheo** [comment]
i think i see the issue and its really fucking weird idk what to make of this
![image](https://github.com/Luna5829/CG-Video-Display/assets/75056493/73c8a259-cf2a-49eb-9fd7-c3a440280128)

**Comment by UntotenTheo** [comment]
in case this is relevant to the issue
![image](https://github.com/Luna5829/CG-Video-Display/assets/75056493/fb2965cc-33c8-40d9-b1ca-d05649c4e0b5)

**Comment by Luna5829** [comment]
ig just update bepinex to the latest version
probably a bepinex issue then

**Comment by UntotenTheo** [comment]
probably, ill go try that

**Comment by Luna5829** [comment]
did it work?

**Comment by UntotenTheo** [comment]
nope, no cigar

i have come to the conclusion that im simply cursed
thank you for your time thoug, idk if ill ask for further help since this seems like its a solo case

**Comment by Luna5829** [comment]
does it give you any error or smt?
could you maybe record it so i can see wat happens

**Comment by UntotenTheo** [comment]
sorry for the late reply

theres no error, and the game just freezes after enough time before crashing
so nothing interesting really, and there isnt anything seemingly decodable

if you insist though i can record a quick run with the crash, shouldnt take too long

**Comment by Luna5829** [comment]
no it's fine
since the issue seems to essentially be unsolvable without being able to replicate it and with no error in logs, i'll close the issue, i guess just don't use that video or smt lol
